---
- name: install postgresql-db
  gather_facts: No
  any_errors_fatal: true
  hosts: _ansible_postgresql
  become: true
  vars_files:
    - secret.yml
  tasks: 
    - name: upgrade all packages
      yum: 
        name: "*"
        state: latest

    - name: Remove docker if installed from CentOS repo
      yum: 
        name: "{{item}}"
        state: removed
      with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine

    - name: install yum utils
      yum:  
        name: "{{item}}"
        state: latest
      with_items:
        - yum-utils
      
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: install Docker
      package: 
        name: docker-ce 
        state: latest

    - name: İnstall pip 
      package:
        name: python3-pip
        state: present
        update_cache: true

    - name: İnstall docker sdk
      pip:
        name: docker
      
    - name: Add user ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: create build directory
      file: 
        path: /home/ec2-user/postgresql
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: copy the sql script
      copy:
        src: /home/ec2-user/ansible/ansible-project/postgres/init.sql
        dest: /home/ec2-user/postgresql

    - name: copy the Dockerfile
      copy:
        src: /home/ec2-user/ansible/ansible-project/postgres/Dockerfile
        dest: /home/ec2-user/postgresql
    
    - name: remove hasant23_postgre container and hasant23/postgre_nf image if exists
      shell: "docker ps -q --filter 'name=hasant23_postgre' && docker stop hasant23_postgre && docker rm -fv hasant23_postgre && docker image rm -f hasant23/postgre_nf || echo 'Not Found'"

    - name: build container image
      docker_image:
        name: hasant23/postgre_nf
        build:
          path: /home/ec2-user/postgresql
        source: build
        state: present

    - name: Launch postgresql docker container
      docker_container:
        name: hasant23_postgre
        image: hasant23/postgre_nf
        state: started
        ports:
          - "5432:5432"
        env: 
          POSTGRES_PASSWORD: "{{password}}"
        volumes:
        - /db-data:/var/lib/postgresql/data   
      register: container_info
    
    - name: print the container info
      debug:
        var: container_info       